### ISSUE TITLE
TraceBack ERRO CAN'T FIX NEED HELP"

### ISSUE THREAD

**Issue by ghost** [c3ypt1c/Lucky-Name-Numbers#5]
Traceback (most recent call last):
File "C:\Users\Zena1\Downloads\engine.py", line 59, in <module>
print ("Your lucky name meaning is: ", meaning[nameMeaning])
IndexError: list index out of range

**Comment by c3ypt1c** [comment]
I'll fix it.....

**Comment by c3ypt1c** [comment]
Fixed....

**Comment by c3ypt1c** [comment]
The solution required you to add the numbers until the size of the string was 1... Otherwise, it wouldn't have worked with names that were bigger than 10... It's documented on the [wiki](https://c3ypt1c.tk/oldwiki/doku.php?id=lucky_numbers) but the code is old and probably buggy... It says 

> The program calculates the sum of all the string per character. Let's say that you are left with 15 when you add the total. The program adds 1 to 5 to get 6. If you were left with 798, after writing gibberish, the program would add 7, 9 and 8 to get 24 then it would add 2 and 4 to get 6

I was planning on changing it but I don't remember the logon details to my own wiki...
